services:
  helloworld:
    image: vy.qle/helloworld:hello
    platform: linux/amd64
    ports:
      - "28080:8080"
    entrypoint: >
      java 
      -XX:+UseParallelGC 
      -XX:MinHeapFreeRatio=5 
      -XX:MaxHeapFreeRatio=10 
      -XX:GCTimeRatio=4 
      -Xms256m 
      -Xmx512m
      -Dlog4j2.formatMsgNoLookups=true
      -Djava.util.logging.manager=org.jboss.logmanager.LogManager 
      -jar /home/jboss/quarkus-run.jar
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-db:5432/kit?currentSchema=kit_manual_test_objs
      KAFKA_BOOTSTRAP_SERVERS: "kafka:19092"
      KATALON_PDP_QUARKUS_SKIP-CHECK: true
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "kit"
      QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT: "http://services-jaeger-all-in-one-1:4317"
      QUARKUS_LOG_CONSOLE_JSON: false
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
        reservations:
          cpus: '1.0'
          memory: 250M